FROM postgres:14.0

ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=schema_dsad

# Copy the initialization script into the Docker image
COPY resources/ddl.sql /docker-entrypoint-initdb.d/

# Expose PostgreSQL port
EXPOSE 5432