FROM postgres:14.0

ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=q2db

# Copy the initialization script into the Docker image
COPY question_2/ddl.sql /docker-entrypoint-initdb.d/

# Expose PostgreSQL port
EXPOSE 5432