version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: webserver
    entrypoint: [ '/opt/airflow/script/entrypoint.sh' ]
    volumes:
      - ./resources:/opt/airflow/resources
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "8080:8080"
    healthcheck:
      test: [ 'CMD-SHELL', "[ -f /opt/airflow/airflow-webserver.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: scheduler
    volumes:
      - ./resources:/opt/airflow/resources
      - ./dags:/opt/airflow/dags
    logging:
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
      webserver:
        condition: service_healthy

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"

  postgres-storage:
    build:
      context: .
      dockerfile: Dockerfile.postgres-storage
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb